name: e_commerce_complete
description: A Flutter e_commerce project using firebase and blocs for state management.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_lib:
    path: ../shared_lib
  flutter_firebase_repository:
    path: ../flutter_firebase_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/half_avo.jpeg
