name: helper_cli
description: A sample command-line application.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  built_value: "^6.1.6"
  built_collection: "^4.0.0"

dev_dependencies:
  test: ^1.0.0
  build_runner: "^1.1.1"
  built_value_generator: "^6.1.6"
